name: Compile production files

on:
  workflow_dispatch:
  push:


jobs:

  # bundle-backpack-board:
  #   runs-on: ubuntu-latest

  #   # These are all the steps that generate the files.
  #   steps:
  #     # Check out the files
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true

  #     # Install the zip command line tool to package up the output
  #     - name: Install zip
  #       uses: montudor/action-zip@v1

  #     # Zip all the documentation. Any files in the PCBWay, PDFs, Renders, and Schematic subfolder
  #     # are automatically included.
  #     - name: Zip project template
  #       run: zip -qq -r backpack-template.zip ./backpack-template/
  #       working-directory: .

  #     # Upload all the zip files to the release. 
  #     - name: Upload release files
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         files: backpack-template.zip


  compile-production-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate full documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/full-outputs.kibot.yaml
          dir: .
          schema: circuits/driver-board.kicad_sch
          board: circuits/driver-board.kicad_pcb

      - name: Fix file permissions for generated files
        run: sudo chown -R $(id -u):$(id -g) ./exports

      - name: Get current date and time
        id: gitstamp
        run: echo "::set-output name=datehash::$(git log -1 --format='%as')-$(git log -1 --pretty=format:%h)"

      # TODO: dynamic expand all images with date and commit hash
      # - name: Copy renders to static folder
      #   run: |
      #     set -e
      #     FONT=".github/artifacts/fonts/RobotoMono-Bold.ttf"
      #     set -v
      #     LABEL="`${{ steps.date.outputs.date }}`\n`git rev-parse --short HEAD`"
      #     convert -background black -fill white -pointsize 12 -font "$FONT" -size 300x36 label:"$LABEL" -bordercolor black -border 3 exports/renders/*.png +swap -append exports/renders/*.png


      - name: Commit renders to static folder
        run: |
          cp -r exports/renders/*.png static/images/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f static/images
          git commit -m "latest renders"
          git push

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: driver-board-${{ steps.gitstamp.outputs.datehash }}
          path: |
            exports/pcb/*.pdf
            exports/pcb/*.jpg
            exports/schematic/*.pdf
            exports/schematic/*.svg
            exports/renders/*.png
            exports/driver-board-3D.step