name: "KiBot - Generate Schematic Outputs"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"


jobs:
  Documentation:
    env:
      timezone: Europe/Copenhagen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/sch-outputs.kibot.yaml
          dir: exports
          schema: circuits/driver-board.kicad_sch
          board: circuits/driver-board.kicad_pcb

      - name: Set ./exports ownership to current user
        run: sudo chown -R $(id -u):$(id -g) ./exports

      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./exports
          git commit -m "workflow generated exports"
          git push

      # # Archive all the artifacts from output and attach to the action's results.
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: driver-board-${{ github.event.inputs.version }}-${{ steps.date_only.outputs.date_only }}
      #     path: exports/**