name: Compile production files

on:
  workflow_dispatch:
  push:


jobs:
  compile-production-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate full documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/full-outputs.kibot.yaml
          dir: .
          schema: circuits/driver-board.kicad_sch
          board: circuits/driver-board.kicad_pcb

      - name: Fix file permissions for generated files
        run: sudo chown -R $(id -u):$(id -g) ./exports

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %T')"

      # TODO: dynamic expand all images with date and commit hash
      # - name: Copy renders to static folder
      #   run: |
      #     set -e
      #     FONT=".github/artifacts/fonts/RobotoMono-Bold.ttf"
      #     set -v
      #     LABEL="`${{ steps.date.outputs.date }}`\n`git rev-parse --short HEAD`"
      #     convert -background black -fill white -pointsize 12 -font "$FONT" -size 300x36 label:"$LABEL" -bordercolor black -border 3 exports/renders/*.png +swap -append exports/renders/*.png

      - name: Copy renders to static folder
        run: cp -r exports/renders static/images

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static/images/*.png
          git commit -m "latest renders"
          git push

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: driver-board-${{ steps.date.outputs.date }}
          path: |
            exports/pcb/*.{pdf,jpg}
            exports/schematic/*.{pdf,svg}
            exports/renders/*.png
            exports/driver-board-3D.step